server:
  port: 9000

spring:
  application:
    name: gateway

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos

    gateway:
      routes:
        - id: system-public-avatar-service
          uri: lb://system
          predicates:
            - Path=/public/system/file/avatar/**

        - id: system-service
          uri: lb://system
          predicates:
            - Path=/api/system/**

        - id: core-service
          uri: lb://core
          predicates:
            - Path=/api/core/**

        - id: core-websocket-service
          uri: lb:ws://core
          predicates:
            - Path=/ws/monitor/**

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            exposedHeaders: "*"
            allowCredentials: false
            maxAge: 3600

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.springframework.cloud.gateway: INFO
    reactor.netty.http.client: INFO